apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ltd-chinchilla-python
  janus-idp.io/tekton: ltd-chinchilla-python
  backstage.io/kubernetes-id: ltd-chinchilla-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ltd-chinchilla-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
